export default [
  {
    key: "0",
    name: "Pay Bills",
    subject: "#2000",
    date: "11/07/23",
    time: "11:30",
  },
  {
    key: "1",
    name: "Reply to emails",
    subject: "Tomi's Email",
    date: "12/06/23",
    time: "09:20",
  },
  {
    key: "3",
    name: "Meeting",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "4",
    name: "Party",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "5",
    name: "Update UI",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "6",
    name: "Server maintanance",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "7",
    name: "Go to the Mall",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "8",
    name: "Pick Up Delivery",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "9",
    name: "Finish Project",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
  {
    key: "10",
    name: "Clean up",
    subject: "With CEO",
    date: "06/07/23",
    time: "11:30",
  },
];
